### ISSUE TITLE
[BUG] Stopped working after Udemy's new URL style

### ISSUE THREAD

**Issue by Vagonn** [nishad/udemy-dl-windows#84] opened 2016-03-27 19:53 UTC
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I used this 5-6 days ago and it worked like a charm. But now (date 27.03.2016) it's stopped working after Udemy changed URL style.

For example, before URL was https://www.udemy.com/the-complete-ios-9-developer-course

But now URL of same course is https://www.udemy.com/the-complete-ios-9-developer-course/learn/v4/content

Thanks

**Comment by nishad** [comment] 2016-03-27 20:06
@Vagonn, This is already reported in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-201330544, and https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-201940523. 

This project is only for windows binary release of https://github.com/nishad/udemy-dl/. Udemy is rolling out new website, and latest PyPI release of https://github.com/nishad/udemy-dl/ is still pending. There will be updated binaries for the next stable PyPI release of `udemy-dl` package (https://pypi.python.org/pypi/udemy-dl). 

Due to this reason, I'm marking this thread as a duplicate of https://github.com/nishad/udemy-dl-windows/issues/63. You can follow that thread for getting any updates regarding next release.

**Closed by nishad** 2016-03-27 20:06 UTC
