### ISSUE TITLE
[BUG] Unable to download udemy videos

### ISSUE THREAD

**Issue by mkranthikmr** [nishad/udemy-dl-windows#66] opened 2016-03-07 21:06 UTC
```
C:\Users\Nagendra\Downloads\udemy-dl-win-2.0.1\udemy-dl-win>udemy-dl.exe https:/
/www.udemy.com/angular-2-jump-start-with-typescript/learn/v4/content
Username/Email: username@gmail.com
Password:
Downloading to: C:\Users\Nagendra\Downloads\udemy-dl-win-2.0.1\udemy-dl-win\angu
lar-2-jump-start-with-typescript

Failed to get course ID
```

**Comment by nishad** [comment] 2016-03-07 21:23
This issue is a duplicate of https://github.com/nishad/udemy-dl-windows/issues/63

**Closed by nishad** 2016-03-07 21:23 UTC
Labels: duplicate, unknown
