### ISSUE TITLE
[BUG] [SocketCore.cc:1006] errorCode=1 SSL/TLS handshake failure: Error: The buffers supplied to a function was too small.

### ISSUE THREAD

**Issue by elvismdev** [nishad/udemy-dl-windows#75] opened 2016-03-19 02:21 UTC
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ X] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Until yesterday it was working fine, today stopped downloading course video files giving this error below.

```
Downloading 007 Video.mp4

03/18 20:08:26 [ERROR] CUID#7 - Download aborted. URI=https://udemy-assets-on-de
mand.udemy.com/...
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://udemy-assets-on-dema
nd.udemy.com/...
  -> [SocketCore.cc:1006] errorCode=1 SSL/TLS handshake failure: Error: The buff
ers supplied to a function was too small.
(80090321)

03/18 20:08:26 [NOTICE] Download GID#73ff9c908222bb0c not complete: C:/Users/Ing
rid/Downloads/udemy-dl-win/course-folder/...

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
73ff9c|ERR |       0B/s|C:/Users/Ingrid/Downloads/udemy-dl-win/course-folder/...

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page
 for details.


C:\Users\Ingrid\Downloads\udemy-dl-win>

```

**Comment by nishad** [comment] 2016-03-19 02:27
This issue is addressed in https://github.com/nishad/udemy-dl-windows/issues/61 and https://github.com/nishad/udemy-dl-windows/issues/30. Possible solution is explained in https://github.com/nishad/udemy-dl-windows/issues/30#issuecomment-167268901. 

Closing this issue since it is a duplicate of https://github.com/nishad/udemy-dl-windows/issues/30

**Closed by nishad** 2016-03-19 02:27 UTC

**Comment by elvismdev** [comment] 2016-03-19 02:36
Deleting `aria2c.exe` fixed the issue for me. It's really weird nothing has changed since yesterday in this windows environment and it just stopped working triggering this error today.

**Comment by nishad** [comment] 2016-03-19 02:51
I'm aware of this issue, it is possibly with the server certificate. SSL handshake errors are often common with udemy servers. You can try with latest aria2c binaries from https://github.com/tatsuhiro-t/aria2/releases/latest. 

Since it is an issue related with aria2, the scope of dealing it inside this project is limited.
