### ISSUE TITLE
[BUG] Error 261 - Expected Quality Not Found Error

### ISSUE THREAD

**Issue by Eshpelin** [nishad/udemy-dl-windows#142] opened 2017-04-19 16:42 UTC
For almost the last 1 week, I have been experiencing Error 261 - something that I am neither being able to fix nor understand. Note that these are courses that I have bought, started, and I have no problems in my Udemy account. After having tried almost all of the advices on the previous threads, I haven't been able to solve it in any way.

This is happening on two individual devices running the latest version of the downloader - and I would love to know if there is any fix to this.

My apologies, but I just found a different thread with the same discussion [HERE](https://github.com/nishad/udemy-dl-windows/issues/139) and a possible BUGFIX [HERE](https://github.com/nishad/udemy-dl-windows/pull/140) at #140 . You can close this thread if this seems inappropriate or unnecessary. I am somehow not bring able to.

----

Way to replicate:

01. Start downloader as Admin
02. Login (works fine)
03. While finding course details, these pop up:

Image here:

![error](https://cloud.githubusercontent.com/assets/23078590/25191284/f66caade-2550-11e7-91a7-96b2e8a17316.PNG)

**Comment by zhedongzheng** [comment] 2017-04-20 13:51
The same problem here

**Comment by Eshpelin** [comment] 2017-04-20 17:29
@nishad - please note the solution on on #140 and see if it can be used in the master. The whole world needs you now :'(

**Comment by waylonmtz** [comment] 2017-04-21 14:20
Are there instructions to generate the executable? I would be happy to do this myself if it was an option.

**Comment by msarun003** [comment] 2017-04-22 16:45
Same problem here too :-( . Any bug fixes ?

**Comment by Ofloo** [comment] 2017-04-23 14:59
[CRITICAL-238] Skipped. Expected quality not found!

I get CRITICAL 238
https://www.udemy.com/hacking-complete

**Comment by IronSuit** [comment] 2017-04-26 00:48
I have the exact same issue, playing with the quality setting doesn't fix it.

**Comment by hariwyzmindz** [comment] 2017-04-26 09:42
Facing Same issue, need help

**Comment by IronSuit** [comment] 2017-04-26 10:37
@hariwyzmindz try this tutorial [https://github.com/nishad/udemy-dl-windows/issues/143](url)

**Comment by hariwyzmindz** [comment] 2017-04-26 12:47
step 8 fails:

C:\Python27\Scripts>pip install -U git+https://github.com/smeggingsmegger/udemy-dl-windows.git@master
Collecting git+https://github.com/smeggingsmegger/udemy-dl-windows.git@master
  Cloning https://github.com/smeggingsmegger/udemy-dl-windows.git (to master) to c:\users\hari\appdata\local\temp\pip-i0b9_z-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: 'c:\\users\\hari\\appdata\\local\\temp\\pip-i0b9_z-build\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\hari\appdata\local\temp\pip-i0b9_z-build\

**Comment by toeknee581** [comment] 2017-04-29 03:45
I was successfully able to do it using the instructions I posted at https://github.com/nishad/udemy-dl-windows/issues/143

**Comment by nishad** [comment] 2017-05-08 16:49
Duplicate of https://github.com/nishad/udemy-dl-windows/issues/139

**Closed by nishad** 2017-05-08 16:49 UTC
Labels: bug, duplicate
