### ISSUE TITLE
Error when attempting to download a course...

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [nishad/udemy-dl-windows#60] opened 2016-02-26 12:49 UTC
```
  -> [SocketCore.cc:1006] errorCode=1 SSL/TLS handshake failure: Error: The revocation function was unable to check revocation because the revocation server was offline.
(80092013)
``

**Comment by moreirawebmaster** [comment] 2016-03-02 23:58
I am also having the same problem.

**Comment by nishad** [comment] 2016-03-07 21:31
Duplicate of https://github.com/nishad/udemy-dl-windows/issues/61

**Closed by nishad** 2016-03-07 21:31 UTC
Labels: duplicate, unknown, wontfix
