### ISSUE TITLE
[BUG] Stopped working and issued a Failed to get course ID

### ISSUE THREAD

**Issue by emi3789** [nishad/udemy-dl-windows#63] opened 2016-03-04 12:31 UTC
I have been using the script without any problems for a while but yesterday it stopped behaving normally and issued the mentioned line: Failed to get course ID.

Udemy have changed their course urls and i guess that is the cause, anyway i hope this is still being worked on and i hope there will be a update with the fix in the near future.

**Comment by d4me94** [comment] 2016-03-04 16:10
Yes, It Is Not Working Now. "FAILED TO GET COURSE ID"

**Comment by yakloin** [comment] 2016-03-06 10:13
Yes I'm having the same issue on all Udemy courses.

"Failed to get course ID"

**Comment by elmatadoor** [comment] 2016-03-14 22:02
is there any fixed for this issus ?

**Comment by christtenator** [comment] 2016-03-15 14:10
Any fixes available for this issue?

**Comment by reza147** [comment] 2016-03-16 09:06
Nishad solve this problem . What are you doing as a owner ?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
you are very lazy .

**Comment by nishad** [comment] 2016-03-16 09:10
@reza147, hope you have seen my response https://github.com/nishad/udemy-dl-windows/issues/71#issuecomment-197177998.

You are working hard to reach our `Hall of Shame` :trophy:

**Comment by reza147** [comment] 2016-03-16 09:49
I am sorry for your mind .

**Comment by nishad** [comment] 2016-03-16 17:17
@emi3789, @d4me94 @yakloin @christtenator, `udemy-dl-windows` is a windows port of https://github.com/nishad/udemy-dl. Only PyPI release of `udemy-dl` will be available as a stable release for this project. This issue is already addressed in `udemy-dl`, but PyPI release is still pending for 0.2.2. Version conversion is mentioned in https://github.com/nishad/udemy-dl-windows#versioning. This project will release stable binaries after the next stable PyPI release of `udemy-dl`.

**Comment by sinip1** [comment] 2016-03-16 19:27
Could you issue working Python script? The one at the repository doesn't actually work. It complaints about "debug" assignment and loading DLException module.

**Comment by nishad** [comment] 2016-03-16 20:06
Already answered in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688

**Comment by elmatadoor** [comment] 2016-03-16 20:10
Hello all , sorry i am new on githup and i don't know how the bugs tracking work here
has the windows version of the udemy downloader been fixed it last issus of no cours ID found or no
please i need answer of : yes or no or trying to fixed it in the next days
soory for the inconvenient

**Comment by nishad** [comment] 2016-03-16 20:11
Already answered in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688

**Comment by elmatadoor** [comment] 2016-03-16 20:14
i have not anderstand what this mean ? where is #63 (comment)
where is the #63 (comment)
my browser not redirect me arround any comment

**Comment by nishad** [comment] 2016-03-16 20:18
Btw, @elmatadoor you are in our **Hall of shame** list due to your outstanding performance in https://github.com/nishad/udemy-dl-windows/issues/71. It doesn't matter if you delete those shameful comments you made in that thread, you are no more welcoming here. Get a life dude.
--

**Comment by elmatadoor** [comment] 2016-03-16 20:25
**@nishad , you have blame me in the old thread about my comment , i have keep my patient and my respect for you and deleting the comment that you have not like , but this time excuse my to tell you that githup is not your website first to tell me you are not welcome here ,
secont think because i am new here and with your genius dont give you the right to tell other people what you want , dont blame me next time and keep your knowledge and genius for you , what ever you are , i dont caer about your tallent your knowledgue your genius you ball of shit python script , ok 
if you need any new good comment from me i am ready

**Comment by nishad** [comment] 2016-03-16 20:28
"The difference between stupidity and genius is that genius has its limits."

- Albert Einstein

**Comment by elmatadoor** [comment] 2016-03-16 20:30
i see since i have discover you last days that you think your self Einstein
mesirable

**Comment by elmatadoor** [comment] 2016-03-16 20:31
i am free for you the next few hours , just tell me what you need the here from me

**Comment by elmatadoor** [comment] 2016-03-16 20:33
#  you are no more welcoming here 
mesirable

**Comment by elmatadoor** [comment] 2016-03-16 20:36
look my old comment and request :  # " i need answer of : yes or no or trying to fixed it in the next days"
not a lot of ball shit as you like

**Comment by seegatesite** [comment] 2016-03-17 02:10
okay..okay. don't fight here...we have to respect @nishad that makes this software. bug fix is not an easy thing to do. If we can not provide assistance to @nishad , better to be silent and awaiting repair script. If you force @nishad to immediately fix this application, you are not the nishad boss. If you can not wait, you better spend money to buy the course from udemy. thx CMIIW :)

**Comment by elmatadoor** [comment] 2016-03-17 08:17
what i was doing since i discover this usfull script is respecting his creator , since he was thinking that creating somme thing usful for the communuty give him the right to blame people and tell theme what ever he want 
## arrogant !!

**Comment by saiman** [comment] 2016-03-17 09:27
@nishad has done a splendid job. @reza147 and @elmatadoor Stop being a d-bag and appreciate his contributions. Did you forget it's an open source project?

**Comment by yakloin** [comment] 2016-03-17 09:48
@saiman totally agree. @nishad has done a fantastic job and been more than helpful on all occasions.

**Comment by elmatadoor** [comment] 2016-03-17 09:52
@saiman @yakloin  , me too i argee that the job is good , does i say somme thing else ??
but look to his comportment with his followers !!

**Comment by rinodung** [comment] 2016-03-23 01:55
@nishad Thanks you very much, you give all of us a lot of premium courses(Event very expensive $300). We have to know that Udemy will always change to fixed this script by change **Preview Mode**, please encourage and appreciate what he has done. Of course, if you can fix it, you should make a pull request instead of leaving a stupid comment.

**Comment by strongnas** [comment] 2016-03-25 08:27
i dont understand very much but this is what i tried, i uninstalled everythin and installed like this

![image](https://cloud.githubusercontent.com/assets/17962711/14040866/cdc0c584-f26b-11e5-812f-1e91b4bf9262.png)

still getting failed to get course id :/

**Comment by rinodung** [comment] 2016-03-25 09:33
@strongnas Udemy will always change to fixed this script by change Preview Mode, please patient and wait for next release!

**Comment by tobias-p** [comment] 2016-03-25 15:20
On monday I could download them without problems, but today I got also the "Failed to get course ID" - Message. Is there already a workaround?
Had my courses in a batch-file with following instructions per course:

`udemy-dl.exe -u my@mail.really -p simplepass123456 -o "C:\udemy-dl-win\NameOfCourse" --lecture-start 1 https://www.udemy.com/Path-of-Course/`

After checking out one of the courses I found out, that the url has changed from 
(old) https://www.udemy.com/Path-of-Course/learn/#
to 
(new)https://www.udemy.com/Path-of-Course/learn/v4/content

Maybe there is the problem? Thx for answers and @nishad : you are doing a great job. Thx man!

**Comment by moreirawebmaster** [comment] 2016-03-26 22:14
After checking out one of the courses I found out, that the url has changed from 
(old) https://www.udemy.com/javafx-tutorial-for-beginners/learn/#
to 
(new)
https://www.udemy.com/javafx-tutorial-for-beginners/learn/v4/t/lecture/3978988


@nishad  you can adjust this change? Thank you.

**Comment by nishad** [comment] 2016-03-27 16:41
@moreirawebmaster Already answered in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688

**Comment by strongnas** [comment] 2016-03-27 18:53
Im sorry, im not understanding is this solved already?

**Comment by nishad** [comment] 2016-03-27 18:54
@strongnas, Already answered in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688

**Comment by elmatadoor** [comment] 2016-03-27 19:10
@ strongnas  , i have the same problem with this gay , he don't know to answer using yes or no !!
i dont know what wrong with him !!

**Comment by moreirawebmaster** [comment] 2016-03-28 01:26
@nishad  #63 (comment) not working, the version no exists(v2.2.0).

**Comment by darkhost21** [comment] 2016-04-04 13:23
Hello,

I struggle for few days with this new error appeared recently with "Failed to get course ID".

I do not wanted to ask for any help because all the help was already here regarding this issue.

Still, i have tried everything. I followed all the threads opened for this issue and i still get the error with course id.

I followed too the wiki and all the steps there with upgrading and no luck. I installed the master tool and no luck. Maybe i am doing something wrong.

Can someone help me with the proper steps to follow to get this sorted out? 

I use the windows version version 201 beta version.

Thank you and have a great day!

Best regards.

**Comment by karlosc** [comment] 2016-04-04 14:10
I am the same as your friend i tried everything, but also on the same problem. a little help necesutamos a help to see what we are doing wrong.

**Comment by karlosc** [comment] 2016-04-04 14:30
This is the way i work
 

C:\udemy-dl-windows-master\dist>udemy-dl.exe -u user -p password --lecture-star 1 --lecture-end 2 -o c:\Course https://www.udemy.com/complete-android-developer-course/

I do wrong

Any help is welcome

**Comment by tobias-p** [comment] 2016-04-04 16:31
guys, as @nishad already told, he updated the normal version and has to wait for another update to create the next windows version. Yeah, it sucks, but we cant do anything other than waiting for the next update...

**Comment by darkhost21** [comment] 2016-04-04 16:46
Ok...so this is the recent news from @nishad ... Good to know. It remains only to wait for the next update. Thanks

**Comment by karlosc** [comment] 2016-04-05 00:45
ok thaks, wait

**Comment by reza147** [comment] 2016-04-08 13:26
Hi . who can download udemy courses now ?

**Comment by tobias-p** [comment] 2016-04-08 14:26
@reza147 read my comment 4 days ago...

**Comment by reza147** [comment] 2016-04-08 14:29
Thank you so much dear (tobias-p) . you always help me . 
ok i should wait for update udemy-dl ?

**Comment by reza147** [comment] 2016-04-09 06:18
Hi Nishad . 
can i ask you when you update udemy-dl for solve this problem ?

**Comment by nishad** [comment] 2016-04-09 07:08
@reza147,  `udemy-dl` is already updated to address this issue.

**Comment by darkhost21** [comment] 2016-04-09 07:58
Hey @nishad ! Udemy-dl is updated for this issue for windows too? And the normal version (as i read up in the thread) which is updated, where can i find it? or how can i use it? on which os i can use it?

**Comment by nishad** [comment] 2016-04-09 08:00
https://github.com/nishad/udemy-dl, is a platform independent Python package.

**Comment by darkhost21** [comment] 2016-04-09 08:03
Ok... so if i instal Python i can use it properly and the "Failed to get course ID" will dissapear?

**Comment by reza147** [comment] 2016-04-09 08:04
Dear Nishad . Now we can download from udemy with new udemy-dl ?

**Comment by nishad** [comment] 2016-04-09 08:05
@darkhost21, @reza147 see https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688

**Comment by yasserdhia** [comment] 2016-04-09 08:09
Nishad..I cant understand about #63 comment..can explan subject step by step?

**Comment by reza147** [comment] 2016-04-09 08:11
yes Nishad i agree with yasserdiha . please more explain #63

**Comment by darkhost21** [comment] 2016-04-09 08:12
Yeah...would be useful some step by step tutorial. I tried last days some python comands regarding udemy-dl but with no luck. i am sure that i missed something... :(

**Comment by nishad** [comment] 2016-04-09 08:12
Probably the best explanation is here, https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-205380729

**Comment by reza147** [comment] 2016-04-09 08:14
Ok nishad but what does it mean exact ? 
you say we can download from udemy ?

**Comment by darkhost21** [comment] 2016-04-09 08:18
It will be better to avoid future questions to have a tutorial regarding this... where to download....what to install....what to write....where to write...cmd...shell...etc... for me is a big mistery....i installed a lot of copyes and upgraded some of them...installed python and followed some commands with no luck....a good tutorial will be awesome...tried many things..

**Comment by nishad** [comment] 2016-04-09 08:20
@reza147, If you can then you can; if you cannot, then you cannot. 
This is what it means.
:+1: 

@darkhost21, In this project, we are not dealing anything about python, at-least end users.

**Comment by reza147** [comment] 2016-04-09 08:23
I am sorry for your polite Nishad ,

**Comment by darkhost21** [comment] 2016-04-09 08:24
Hey @nishad ! i don't understand you why do you avoid the "answers"..and put us in more mistery...your reasons....but how about the tutorial...you did not answer regarding this. not many knows how to properly make this to work

**Comment by nishad** [comment] 2016-04-09 08:26
@darkhost21, What do you mean by a tutorial ? Everything related to the usage of this tool is explained here. https://github.com/nishad/udemy-dl-windows/blob/master/README.md

**Comment by darkhost21** [comment] 2016-04-09 08:28
I followed that many times and i still get the course id error.

**Comment by nishad** [comment] 2016-04-09 08:30
@darkhost21, That's why this thread is still open.

**Comment by darkhost21** [comment] 2016-04-09 08:32
OK .. so the error is still there....and maybe it will be fixed in later updates no?

**Comment by nishad** [comment] 2016-04-09 08:49
I guess, still there are a lot of users who got confused with what this project is all about.

This project is a Windows binary distribution of https://pypi.python.org/pypi/udemy-dl. 

Windows standalone binaries are provided to help Windows users to avoid the pain of installing Python and all dependencies. Which also helps novice users from debugging Python related issues. 

If there is a new release for https://pypi.python.org/pypi/udemy-dl, this project will use that to produce new windows binaries (or `udemy-dl.exe`, as you call it).

Next stable release of https://pypi.python.org/pypi/udemy-dl will be `v0.2.2`, which is still under development. You can track the progress of this project here https://github.com/nishad/udemy-dl/milestones

Hope this helps all our curious users understand the nature of this project.

**Comment by elmatadoor** [comment] 2016-04-09 11:06
@nishad alwasy the same problem with this gay and his handicap of communication
always redirect newbies to his ball of chit calling : #63 (comment) ; and the problem no one , no one understand what does this F***************  #63 (comment) mean
i have ask the same question quindly in the old comments he say to me , you are not welcome here
and voila , he is always idiot , can't explain to people with a simple tutorial how it work and how to bypass :  failed to get course id

**Comment by tobias-p** [comment] 2016-04-09 11:55
to all who have problems using the udemy-dl windows version:

In about 60 mins I will post here a step-by-step guide, how to install and use the platform independent version of udemy.

**Comment by nishad** [comment] 2016-04-09 11:58
@tobias-p That is a different project, better you can contribute that guide to https://github.com/nishad/udemy-dl.

This project is exclusively for windows binaries of https://pypi.python.org/pypi/udemy-dl

**Comment by tobias-p** [comment] 2016-04-09 12:05
I understand that @nishad but since the windows users are all here and most of them are not able to do this on their own, I still would like to post the guide here.

But feel free to use the guide in the platform independent part of the project :+1:

**Comment by nishad** [comment] 2016-04-09 12:09
@thobias That will make this project complected, people who want to use that python package can use it. This project is exclusively for windows binary distribution. I don't want to entertain unrelated issue reports here. For pip and python https://github.com/nishad/udemy-dl is the repository.

**Comment by darkhost21** [comment] 2016-04-09 12:12
Still a mistery for most users here i think...@tobias-p i think your guide will be usefull for most of the users who do not understand how things works

**Comment by nishad** [comment] 2016-04-09 12:18
@darkhost21, this project intended to be only for windows binary distribution of https://github.com/nishad/udemy-dl. It is clearly mentioned in https://github.com/nishad/udemy-dl-windows/blob/master/README.md

There is no Python or PIP involved in here, and doing so will make all different kind of issues reported to this project. As a maintainer, it is important for me to keep these two projects independent.

**Comment by darkhost21** [comment] 2016-04-09 12:22
So would be nice to have a guide for both..not the one in readme.md because i think that readme file is tested many times and the issue is still there...here can be a windows guide and in the other version in another thread another guide for pip..idk...keep threads independent by making advanced tutorials for each one

**Comment by darkhost21** [comment] 2016-04-09 12:28
There will be always comments with questions over questions if an advanced guide is not maded...this is my opinion....lots of people followed those instructions and still people are posting here because of the error..if the pip version is working with no error id make a guide to follow...and maybe people will start using that version instead of this and no errors will be anymore

**Comment by nishad** [comment] 2016-04-09 12:29
@darkhost21, I guess, I made it clear. Managing issues is really a problem if these two projects are mixed together.

**This is a windows binary distribution of udemy-dl**, so it should keep as it is instead of mixing up with udemy-dl Python package.

Most of the users are so novice that they will never going to understand that difference and all Python related issues will be flooded here. 

As https://github.com/nishad/udemy-dl-windows/blob/master/README.md says **this is a windows utility** based on https://github.com/nishad/udemy-dl.

**Comment by darkhost21** [comment] 2016-04-09 12:34
Yeah..i understand that you don`t want to mix up projects..is normal and is understandable...please make an advanced step by step tutorial for pip in the python version in another thread instead..idk..a thread opened for pip version...if the pip version is working properly i would gladely follow that thread because in windows version i always get failed to get course id

**Comment by tobias-p** [comment] 2016-04-09 12:35
OK, i will make the guide in the other project and try to link to that guide then ;)

**Comment by darkhost21** [comment] 2016-04-09 12:36
That would be excelent and usefull...i do not have a problem to follow another method for this to work

**Comment by nishad** [comment] 2016-04-09 12:39
@darkhost21, go to https://github.com/nishad/udemy-dl, there are instructions already.

@tobias-p, You can create a page in https://github.com/nishad/udemy-dl/wiki for windows usage, but please don't link it here. This project got nothing to do with Python or PIP. If anyone want to use a python package they have to go to https://github.com/nishad/udemy-dl and utilize resources available there.

**Comment by reza147** [comment] 2016-04-09 12:45
tobias-p  where i can find your guide ?

**Comment by elmatadoor** [comment] 2016-04-09 12:58
Can Somme one answer my question with just on word#  "yes or no "
does this tool work ?
wich version is working fine ?#  windows version or # python version
i have the same error in both version : Failed to get course ID
about python version i have install all dependency as youtube-dl .................
my question is not for this gay @nishad

**Comment by nishad** [comment] 2016-08-14 18:31
Fixed with https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.1

**Closed by nishad** 2016-08-14 18:31 UTC
Labels: bug, unknown
